package com.pvz2.model.enums;

/**
 * انواع گیاهان بازی — بر مبنای فایل plants.xlsx به‌روزرسانی شده.
 * 69 گیاه کامل.
 */
public enum PlantType {
    // Sun Producers
    SUNFLOWER, TWIN_SUNFLOWER, SUN_SHROOM, PRIMAL_SUNFLOWER, GOLD_BLOOM,
    // Shooters / Pea Family
    PEASHOOTER, REPEATER, THREEPEATER, SNOW_PEA, ROTOBAGA,
    PEA_POD, SPLIT_PEA, CITRON, CAULIPOWER, ELECTRIC_BLUEBERRY,
    BOWLING_BULB, CACTUS, FIRE_PEASHOOTER, STARFRUIT, GOO_PEASHOOTER,
    MEGA_GATLING_PEA,
    // Lobbers
    SEA_SHROOM, PUFF_SHROOM, FUME_SHROOM,
    CABBAGE_PULT, KERNEL_PULT, MELON_PULT, WINTER_MELON, PEPPER_PULT,
    // Explosives
    POTATO_MINE, PRIMAL_POTATO_MINE, CHERRY_BOMB, SQUASH, GRAPESHOT,
    JALAPENO, DOOM_SHROOM, TANGLE_KELP, ICEBERG_LETTUCE,
    // Melee
    BONK_CHOY, PHAT_BEET, CHOMPER, WASABI_WHIP, KIWIBEAST,
    // Wall-nuts / Defenders
    WALL_NUT, TALL_NUT, ENDURIAN, GARLIC, SWEET_POTATO,
    EXPLODE_O_NUT, PUMPKIN,
    // Modifiers / Support
    SUN_BEAN, TORCHWOOD, MAGNET_SHROOM, HYPNO_SHROOM, CAT_TAIL,
    IMITATER, ICE_SHROOM, LILY_PAD, HOT_POTATO, GRAVE_BUSTER,
    // Mints
    ENLIGHTEN_MINT, APPEASE_MINT, ARMA_MINT, BOMBARD_MINT,
    ENFORCE_MINT, REINFORCE_MINT, ENCHANT_MINT, PIERCE_MINT, CATTAIL_MINT,
    // Minigame-only
    WALLNUT_BOWLING, EXPLODE_O_NUT_BOWLING, BIG_WALLNUT
}
